### ISSUE TITLE
Allow user to upload photograph for a note #15

### ISSUE THREAD

**Issue by JoshKallagunta** [JoshKallagunta/lmnop#14]
Display photographs with the associated note. There are security issues with allowing users to upload files, how will you deal with that? How will you manage how many images a user uploads, and manage space on your server?

**Comment by Anachronaut** [comment]
@JoshKallagunta, @travelingspace, @IsmaelFarah101 want to double-check this? Should be good to go. In photo_upload branch.

Added photo field, delete and save function to Note model, added NoteEditPhotoForm, changed note_list.html Note title link to note_detail, added photo display and NoteEditPhotoForm instance on note_detail.html and form support to views_notes.py, and media folder support to lmnop_project/settings.py, urls.py

**Comment by Anachronaut** [comment]
Pulled, merged photo_upload branch to master. Closing.
