### ISSUE TITLE
User can save a rating for the shows they create notes for #6

### ISSUE THREAD

**Issue by IsmaelFarah101** [JoshKallagunta/lmnop#8]
Example - thumbs up/thumbs down; or give a number of stars 1-5 for a show.
Or maybe a user can rate a show without writing a note?

**Comment by Anachronaut** [comment]
@JoshKallagunta Added the rating functionality in the first sentence, but not the second. Also, changed the note detail page so unauthorized users can't change the note photo/rating. Might want to see the IF block in note_details.html for your user page problem, @IsmaelFarah101.

note_rating branch

**Comment by Anachronaut** [comment]
Merged
